# -*- coding: utf-8 -*-
"""Language Detection Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lt3h-I6Z_cgzdwKs_BW-c0V_e8NM1Zv9
"""

import numpy as np
import pandas as pd

ld  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/tha scale ml project /Language Detection Model/Language Data.csv')

ld

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB

data

data.isnull().sum()

data.describe()

data['language'].value_counts()

x = np.array(data['Text'])
y = np.array(data['language'])

print(x)

print(y)

cv = CountVectorizer()
x = cv.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

print(x_train)

model = MultinomialNB()
model.fit(x_train, y_train)
model.score(x_test, y_test)

visitor = input('Enter a Text: ')
data = cv.transform([visitor]).toarray()
output = model.predict(data)
print(output)







